Page/case studies
OgUrbana/Portfolio pull request #4
Opened 2023-09-19 17:42 UTC by OgUrbana

- Created Case Page
- Created Jobit and Morrent Page
- Made it dynamically so it's easy to create multiple case study pages that follow the same layout.

![image](https://github.com/OgUrbana/Portfolio/assets/41495671/15c94a5b-1e83-4cae-b0d0-d79f45f79b9a)
![image](https://github.com/OgUrbana/Portfolio/assets/41495671/a6c3b913-f642-4468-851b-92a23183ba09)

2023-09-19 21:06 UTC, cdsalty commented on components/Case/CaseLayout.tsx
> +          <hgroup className='flex flex-col gap-2'>
Interesting that you are using `hgroup` here. I believe a `div` should be fine in this case.

2023-09-19 21:13 UTC, cdsalty commented on app/case/jobit/page.tsx
challenges, description, learnings, etc. These all need to be put inside a separate file and imported inside here. There should be a very minimal amount of code in this component once you import the data and pass your props accordingly.

2023-09-19 21:13 UTC, cdsalty commented on app/case/jobit/page.tsx
> +const Page = () => {
Bring your projects inside your function.
Rename your "Page" so it's more descriptive regarding it's purpose. You could name it "CaseLayout.tsx"

2023-09-19 21:13 UTC, cdsalty commented on app/case/morrent/page.tsx
Same thing here.

2023-09-19 21:14 UTC, cdsalty commented on app/case/page.tsx
Same thing here.

We also need to review the correct use of HTML Semantics. We don't need everything in a <section>, this defeats the purpose. It's perfectly okay to have <divs> within a section. Take a look at the link I am referencing for a quick refresher. 

https://queen.raae.codes/emails/2022-10-10-semantic-react/

2023-09-19 21:14 UTC, cdsalty commented on app/case/page.tsx
> +import Jobit from '@/public/projects/desktop/Jobit.png';
Should not be separate imports... They should both be coming from one main index file.

2023-09-19 21:14 UTC, cdsalty commented on app/case/page.tsx
> +            </Link>
When you map over the data, create a separate component to pass in instead of returning it here. For example, return a <Card /> that passes the props such as title, color, desc.

2023-09-19 21:14 UTC, cdsalty commented on app/layout.tsx
Your font styles should go inside your globals.css or for any tailwind configurations, inside the tailwind.config

2023-09-19 21:14 UTC, cdsalty commented on app/page.tsx
You don't need to separate your components with <Section> tags here.

2023-09-19 21:14 UTC, cdsalty commented on components/Case/CaseLayout.tsx
Same thing here. Remove all the hard-coded data into a separate component.

2023-09-19 21:14 UTC, cdsalty commented on components/Case/CaseLayout.tsx
> +import SuccessIcon from '@/public/cases/success.png';
All of these should be imported from the same index. Create one root index that will import and export the icons.

2023-09-19 21:14 UTC, cdsalty commented on components/Case/CaseLayout.tsx
> +}) => {
Why are you not importing the types as you have done in other areas of your code? Place all of this with your types

2023-09-19 21:14 UTC, cdsalty commented on components/Case/CaseLayout.tsx
> +        </section>
This should be a separate component. You want to map over your data and return a component and then pass the appropriate props. There is way to much unnecessary clutter in the code that we can clean up.

2023-09-19 21:14 UTC, cdsalty commented on components/Case/CaseLayout.tsx
> +      <section className='bg-background-1'>
Each section could be a separate component to reduce the amount of code in one file.

2023-09-19 21:14 UTC, cdsalty commented on components/Case/CaseLayout.tsx
> +                <section key={`challenge-${index}`} className='flex gap-3'>
Another place for you to import a separate component that your map creates.

2023-09-19 21:14 UTC, cdsalty commented on components/Case/TechItem.tsx
This is a perfect example of making a component to reuse in your code. Why are you not doing this in more of your code? Great job!

2023-09-19 21:14 UTC, cdsalty commented on components/Case/Technologies.tsx
Move all your icons into one index and import from there. 
Move all hard-coded data outside into a separate folder.

2023-09-19 21:15 UTC, cdsalty commented on components/Case/types.d.ts
You should put all of your types in one types folder.

2023-09-19 21:15 UTC, cdsalty commented on components/Case/types.d.ts
> +export type Tech =
Same here

2023-09-19 21:15 UTC, cdsalty commented on components/GetInTouch.tsx
> +            alt='contact background'
Be more descriptive with your alt tags. You have same alt tag appearing in both images.

2023-09-19 21:15 UTC, cdsalty commented on components/Home/Hero.tsx
> +        </video>
I was under the impression you were using an SVG here... Be careful how this will render on slower settings/wifi, phones, etc...

2023-09-19 21:15 UTC, cdsalty commented on components/Home/Reviews.tsx
>        <button
One thing to consider here is to create a reusable button and pass down the props accordingly. This will make the code much more consistent across your application.

2023-09-19 21:16 UTC, cdsalty commented on components/Home/Reviews.tsx
>            >
There is too much repeating code. This is typically a good sign that you clean it up by creating reusable components.

2023-09-19 21:22 UTC, cdsalty requested changes
Hi @OgUrbana, Really impressive—well done! Please review the following suggestions to refine your code further... There is a lot we can clean up and refactor. You got this!

**Typewriter Effect & Font Color:** While the typewriter effect is engaging, it may be a bit too much. The blue font also seems overwhelming. Consider simplifying these elements.

**Hero SVG Effects:** The current effects are attention-grabbing but could be subtler. Please consider slowing down the movements.

**My Skills Section:** While visually appealing, the percentage breakdown for JavaScript and TypeScript could be a hindrance in a professional setting. It's advisable to omit this section, as the design serves specific purposes that should not be deviated from. (You don't want to say you're 79% anything....)

**Boilerplate for Unfinished Sections:** Create placeholder content for the 'Contact' section and any other in-progress areas to avoid 404 errors during the review process.

**Dark Mode:** The implementation is clean and not overly complex—excellent work!

For this Pull Request, focus only on implementing these suggestions, given that it's already a substantial commit. Any additional features should be part of a separate branch and Pull Request.

If you have any questions or require further clarification, feel free to reach out. Keep up the excellent work!

2023-09-21 14:35 UTC, OgUrbana commented on components/Home/Hero.tsx
> +        </video>
I'll work on converting it into an SVG !

2023-09-21 20:39 UTC, cdsalty commented on components/Case/CaseLayout.tsx
Be sure to review your HTML Semantics...

2023-09-21 20:40 UTC, cdsalty commented on components/Case/CaseProblem.tsx
Same HTML Semantics

2023-09-21 20:44 UTC, cdsalty commented on components/GetInTouch.tsx
> +import React from 'react';
Remove unnecessary imports

2023-09-21 21:02 UTC, cdsalty commented on components/Case/CaseDiscovery.tsx
> +      </article>
Break your components down as much as possible. Also, please don't use hard-coded colors. You will configure this in your tailwind config.

2023-09-21 21:03 UTC, cdsalty commented on components/Case/CaseLayout.tsx
> +    </section>
Remember your html semantics

2023-09-21 21:04 UTC, cdsalty commented on components/Case/index.ts
Love it!

2023-09-21 21:09 UTC, cdsalty requested changes
Be sure to go throughout the entire app and update your HTML Semantics, refactor the duplicated code discussed and address the other suggestions I included. Let me know once you have it complete and I will give it another look. You're doing fantastic. Keep it up!

2023-09-21 21:10 UTC, cdsalty commented
Once you complete the changes @OgUrbana, make sure to update the label accordingly so we know it's ready to be reviewed again. Great job again!

2023-09-22 03:25 UTC, cdsalty commented
@OgUrbana, hey bud, be sure to reach out and let me know if you need anything. I'm always happy to help! Cheers!

2023-09-23 18:30 UTC, brandonetter requested changes
The code is fantastic, but I do have some comments and additions to Christopher's suggestions design-wise:

### I agree wholeheartedly on not marking yourself as "75%" skilled in anything. If this is a portfolio to land you a job as a web developer- I wouldn't put anything below 90% if it's a webdev skill. The effect is fantastic but I agree it might work against you.

### Your subheading text at a medium breakpoint looks a little small. This is nice for mobile but can and should still remain a little larger at this breakpoint:

![image](https://github.com/OgUrbana/Portfolio/assets/4108484/611fdec4-b278-43c0-b631-365c6a7af849)

### Animated video:

The animation is <100kb, webm is a good format. I don't think you'll get a significantly smaller SVG- but if you can then absolutely reduce filesize on elements like this. Making in an SVG and calling it via an Image tag would be extra helpful as Mentor Christopher suggests especially because this is your 'hero' image and you'd likely want to mark it as "Priority".

https://nextjs.org/docs/app/building-your-application/optimizing/images#priority

This will increase performance of your LCP because that image will be prioritized when loading your site.

### Emphasizing content with font-size:

![image](https://github.com/OgUrbana/Portfolio/assets/4108484/b5a14cab-668d-4f02-a382-0a42bff6cdb4)

I'd increase the font size of the dates/your role to 24px like in the design. It will help to emphasize those sections. 

Honestly this is fantastic work.

### No edge-to-edge banner

![image](https://github.com/OgUrbana/Portfolio/assets/4108484/dfc1daac-2319-404e-8dea-98eca41448c5)

I notice this isn't included in your design. Is that Intentional?

2023-09-24 00:25 UTC, OgUrbana commented
> The code is fantastic, but I do have some comments and additions to Christopher's suggestions design-wise:
> 
> ### I agree wholeheartedly on not marking yourself as "75%" skilled in anything. If this is a portfolio to land you a job as a web developer- I wouldn't put anything below 90% if it's a webdev skill. The effect is fantastic but I agree it might work against you.
> ### Your subheading text at a medium breakpoint looks a little small. This is nice for mobile but can and should still remain a little larger at this breakpoint:
> ![image](https://private-user-images.githubusercontent.com/4108484/270124821-611fdec4-b278-43c0-b631-365c6a7af849.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTU1MTQyNDksIm5iZiI6MTY5NTUxMzk0OSwicGF0aCI6Ii80MTA4NDg0LzI3MDEyNDgyMS02MTFmZGVjNC1iMjc4LTQzYzAtYjYzMS0zNjVjNmE3YWY4NDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzA5MjRUMDAwNTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTc2ZDYzMGQyMTU0MWExZmFiODI1YzFjZmMxNGQyOTI2MmU0ZGFmYWJkMmExZTI4MzAyOTlhOTFiNTZiNDhmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kxVYmqT-2zNX1bKgQwv9UpNAbbUDtw_Y60sBqORSMYk)
> 
> ### Animated video:
> The animation is <100kb, webm is a good format. I don't think you'll get a significantly smaller SVG- but if you can then absolutely reduce filesize on elements like this. Making in an SVG and calling it via an Image tag would be extra helpful as Mentor Christopher suggests especially because this is your 'hero' image and you'd likely want to mark it as "Priority".
> 
> https://nextjs.org/docs/app/building-your-application/optimizing/images#priority
> 
> This will increase performance of your LCP because that image will be prioritized when loading your site.
> 
> ### Emphasizing content with font-size:
> ![image](https://private-user-images.githubusercontent.com/4108484/270125383-b5a14cab-668d-4f02-a382-0a42bff6cdb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTU1MTQyNDksIm5iZiI6MTY5NTUxMzk0OSwicGF0aCI6Ii80MTA4NDg0LzI3MDEyNTM4My1iNWExNGNhYi02NjhkLTRmMDItYTM4Mi0wYTQyYmZmNmNkYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzA5MjRUMDAwNTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhjNjdlMzZjYWI3MTRlZDJkZTkyZWM1YWQzOGUwMGRkYmFlNjMzMjAzOGYzYjY2NTNmYTMzMDRiMDk1MTU5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oKZxEf8tGoPBx6d9OyhR__MsEDYf7DK_tLTx25U2Ur8)
> 
> I'd increase the font size of the dates/your role to 24px like in the design. It will help to emphasize those sections.
> 
> Honestly this is fantastic work.
> 
> ### No edge-to-edge banner
> ![image](https://private-user-images.githubusercontent.com/4108484/270125451-dfc1daac-2319-404e-8dea-98eca41448c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTU1MTQyNDksIm5iZiI6MTY5NTUxMzk0OSwicGF0aCI6Ii80MTA4NDg0LzI3MDEyNTQ1MS1kZmMxZGFhYy0yMzE5LTQwNGUtOGRlYS05OGVjYTQxNDQ4YzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzA5MjRUMDAwNTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWNlY2E1OTY2NGJhMDc1YWRmNGQ5MGMzNTlhYmIwMWM3MzJjMGJlZDYwNjkwM2Q3Yjc2YjI2NDUyNzMzMWNkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yHG1VsLBnHTRbdqOsjtacg__bMao_3TSbpcbGJtEGaE)
> 
> I notice this isn't included in your design. Is that Intentional?

Hi Brandon, thank you for the kind words!

### Edge to Edge banner

With the edge-to-edge banner, I'm trying to figure out how to do it properly, while making it look good without just having a repeating image that has a clean cut-off for each time it's repeated. 
I'm on an ultrawide screen and so I was wondering how to handle those extra-large screens, do I just cut off the image, or do I repeat it?
Also, I'm not sure how to get that type of image for every single project, in this case, the only other one is Jobit 🤣.

### Skills Section

I completely agree about the skills section, it was originally brought up by Mentor Nassim when it was first merged, and I agree with all of you, and will change it.

### Hero Video

I will be converting this to an SVG, I was thinking either Framer Motion or using svgator.
edit: found out that Adobe Creative Cloud has adobe animate now where you can work directly and export as SVG's, I'll be using that

2023-09-24 00:39 UTC, brandonetter commented
@OgUrbana 

https://codesandbox.io/p/sandbox/nice-sinoussi-ykhns7

You can pop this out using this button in the top-right:
![image](https://github.com/OgUrbana/Portfolio/assets/4108484/1bb4afae-52f7-4cc5-811d-2b24364d4dfe)


I'm setting a div to the full width of the screen, and using an image with "fill=true" inside to make it the div background. You can control the way that image displays using all the 'object' classes from tailwind and by changing the h/w of the div.

Glad you have a gameplan for the animated SVG. I'll merge this for now if you'd like. Let me know :)

2023-09-24 00:43 UTC, OgUrbana commented
> @OgUrbana
> 
> https://codesandbox.io/p/sandbox/nice-sinoussi-ykhns7
> 
> You can pop this out using this button in the top-right: ![image](https://private-user-images.githubusercontent.com/4108484/270138811-1bb4afae-52f7-4cc5-811d-2b24364d4dfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTU1MTYzMjAsIm5iZiI6MTY5NTUxNjAyMCwicGF0aCI6Ii80MTA4NDg0LzI3MDEzODgxMS0xYmI0YWZhZS01MmY3LTRjYzUtODExZC0yYjI0MzY0ZDRkZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzA5MjRUMDA0MDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2M1ZTUzYTc3ZTYwZmQ3ZWJkMmU0ZTlmMjJmNjUyNGJkYTNhNzYyOWQ3MjhhNDIwNDM0NzQ3YTNiZTMxYTA4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e6Xb9ElyYMjjwhDoUuBVXkRCyLK3M6VnrA91_MM590s)
> 
> I'm setting a div to the full width of the screen, and using an image with "fill=true" inside to make it the div background. You can control the way that image displays using all the 'object' classes from tailwind and by changing the h/w of the div.
> 
> Glad you have a gameplan for the animated SVG. I'll merge this for now if you'd like. Let me know :)

Thank you! I'll give this a shot 😁
If you could merge it now that'd be great, I will change the animated SVG and add the edge-to-edge design in a separate PR.

2023-09-24 00:44 UTC, merged